name: Matrix Demo
on: 
  push:
  workflow_dispatch:

jobs:
  build:
    strategy:
      matrix:
        node-version: [21, 22, 23]
        operating-system: [ubuntu-latest, windows-latest]

    runs-on: ${{ matrix.operating-system }}
    steps:
      - name: Get code
        uses: actions/checkout@v4
      - name: Install NodeJS
        uses: actions/setup-node@v4
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install deps
        run: npm ci
      - name: Build project
        run: npm run build